via_options:
  address: ENV['EMAIL_ADDRESS']
  port: ENV['EMAIL_PORT']
  user_name: ENV['EMAIL_USERNAME']
  password: ENV['EMAIL_PASSWORD']
  authentication: ENV['EMAIL_AUTHENTICATION']
  domain: ENV['EMAIL_DOMAIN']
